### ISSUE TITLE
[BUG]: incompatible pydantic version in pyproject.toml

### ISSUE THREAD

**Issue by zac-wang-nv** [NVIDIA/AgentIQ#74]
### Version

1.0.0

### Which installation method(s) does this occur on?

PyPi

### Describe the bug.

arize-phoenix 6.1 or 6.2 uses older versions of strawberry which uses a deprecated type in pydantic, which will cause an error if uv resolves to install pydantic 2.11.x instead of 2.10.x(both are permissive in pyproject.toml)
Error message,
```
ImportError: cannot import name 'is_new_type' from 'pydantic._internal._typing_extra'
Did you mean: 'is_none_type'?
```
Upgrade to the latest version of arize-phoenix will resolve this issue. or add a constart to pydantic version to be `<2.11`

### Minimum reproducible example

```shell
pip install agentiq pydantic==2.11.0
python -c 'import phoenix'
```

### Relevant log output

<details><summary>Click here to see error details</summary><pre>

 [Paste the error here, it will be hidden by default]

</pre></details>

### Code of Conduct

- [x] I agree to follow AgentIQ' Code of Conduct
- [x] I have searched the [open bugs](https://github.com/NVIDIA/AgentIQ/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by dagardner-nv** [comment]
@zzzacwork can you provide the `uv` commands you used which resulted in `pydantic` 2.11 installed? Specifically if there is some combination of extras or groups that resulted in pydantic 2.11.

It is my understanding that when we state our dependency as `pydantic~=2.10` we are stating that AgentIQ works with any version of `pydantic >=2.10,<3`. However on my system `uv` always solves version 2.10 of pydantic, presumably after examining the constraints of the other packages on the system.

This is my repro:
```bash
rm uv.lock # not needed but just in case
uv venv -p 3.12 --seed .venv
source .venv/bin/activate
uv sync 
uv pip list | grep pydantic 
# This gives me pydantic 2.10.6

uv pip install pydantic==2.11.*
uv sync # at this point pydantic is downgraded back to 2.10.6
```

**Comment by zac-wang-nv** [comment]
Thanks for taking time and look into it, if I do the following
```
uv venv -p 3.12 --seed .venv
uv pip install -e . 
pip list | grep pydantic
```
it will solve to `pydantic==2.11.3`

**Comment by akshayanv** [comment]
@dagardner-nv any news on this?

**Comment by dagardner-nv** [comment]
The issue appears to be a behavioral difference between `uv sync` (installs 2.10) and `uv pip install -e . ` (installs 2.11)
